In [3]:
#ML Project: Spam eMail Detection with Naive Bayes Classifiers
import pandas as pd
import numpy as np
import seaborn as sns


In [5]:
df=pd.read_csv("emails.csv")

In [6]:
df.head()

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [7]:
df['spam'].value_counts() #checking how many spams/hams

0    4360
1    1368
Name: spam, dtype: int64

In [8]:
df.drop_duplicates(inplace= True)

In [9]:
df['spam'].value_counts()#again chack after deleting 

0    4327
1    1368
Name: spam, dtype: int64

In [10]:
df.isnull().sum()


text    0
spam    0
dtype: int64

In [11]:
#split
x=df.text.values

In [12]:
y=df.spam.values

In [13]:
df

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5695 rows x 2 columns]

In [14]:
#test,test data split
from sklearn.model_selection import train_test_split

In [16]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2)

In [20]:
#text data converting to numnaric form

from sklearn.feature_extraction.text import CountVectorizer

In [21]:
cv=CountVectorizer()
x_train=cv.fit_transform(xtrain)


In [22]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [23]:
#ML_Algorithm
from sklearn.naive_bayes import MultinomialNB

In [24]:
model=MultinomialNB()
model.fit(x_train,ytrain)

MultinomialNB()

In [25]:
x_test=cv.transform(xtest)#numaric to text conversion

In [26]:
x_test.toarray()

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [28]:
model.score(x_test,ytest) #wowAgreatScore :D

0.9859525899912204

In [47]:
emails=['wow you won 100000$ USD  plus Iphone x givaway please click the link below','Hello Tahsin, you have been selected for the contest']

In [48]:
cv_emails=cv.transform(emails)

In [49]:
model.predict(cv_emails)

array([1, 0], dtype=int64)

In [50]:
#1-spam,0-Ham - its working perfectly ! :3